[package]
name = "zellinotes-recipe-service-rust"
version = "0.1.0"
authors = ["julian <ju851zel@htwg-konstanz.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
